watch:
    directories:
        - src
        - tests
    fileMask: '*.php'
notifications:
    passingTests: false
    failingTests: false
phpunit:
    binaryPath: ./vendor/bin/phpunit
    arguments: '-c phpunit.xml.dist --verbose --stop-on-failure --testdox --testsuite unit'
    timeout: 180
